### ISSUE TITLE
Opportunity Card 

### ISSUE THREAD

**Issue by JillianQuinn** [hack4impact-calpoly/pryac#37]
Requirements:
- create a reusable component **class** that we can use throughout the web app ( #15 #20 )
- `.\Components\OpportunityCard\OpportunityCard.js`
- `.\Components\OpportunityCard\OpportunityCard.css`
- The card should display:
    - Opportunity title
    - description (limit to 40 chars and "...")
    - picture
    - view details button
    - Area of Interest icons ( https://www.flaticon.com/collections/15845366 )

<img width="284" alt="Screen Shot 2021-01-18 at 7 26 05 PM" src="https://user-images.githubusercontent.com/25594364/104984139-05754b80-59c3-11eb-95f7-4e855774b9c5.png">

**Comment by JillianQuinn** [comment]
Just talked with Ryan, and he was worried about it looking too cluttery with too many images so he changed his mind and actually would like to just have the icon as the image instead of having both the photos and the little icons at the bottom of the page

**Comment by tessa-tapmongkol** [comment]
Okay! I will fix the opportunity card once I'm done with the anonymous dashboard
